"""Persistence interfaces; adapters may be SQLite, PostgreSQL, or remote stores."""

from __future__ import annotations

from typing import Protocol

from agentgate.contracts import Result, Run, Trace


class AgentGateRepository(Protocol):
    def save_run(self, run: Run) -> None: ...
    def get_run(self, run_id: str) -> Run | None: ...
    def list_runs(self, limit: int = 50) -> list[Run]: ...
    def save_trace(self, trace: Trace) -> None: ...
    def get_trace(self, run_id: str, case_id: str) -> Trace | None: ...
    def list_traces(self, run_id: str) -> list[Trace]: ...
    def save_results(self, results: list[Result]) -> None: ...
    def list_results(self, run_id: str) -> list[Result]: ...
    def put_business_state(self, namespace: str, key: str, value: dict) -> None: ...
    def get_business_state(self, namespace: str, key: str) -> dict | None: ...
